swiftpro:
    #list of controllers
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 10

    joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint1
      pid: {p: 40.0, i: 10.0}
      
    joint2_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint2
      pid: {p: 40.0, i: 10.0}

    joint3_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint3
      pid: {p: 40.0, i: 10.0}

    joint4_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint4
      pid: {p: 2.0, i: 1.0}

    joint5_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint5
      pid: {p: 2.0, i: 1.0}

    joint6_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint6
      pid: {p: 1.0, i: 1.0}

    joint7_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint7
      pid: {p: 1.0, i: 1.0}

    joint8_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint8
      pid: {p: 1.0, i: 1.0}
    virtual_end_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/virtual_end_joint
      pid: {p: 1.0, i: 1.0}
    joint9_position_controller:
      type: effort_controllers/JointPositionController
      joint: swiftpro/arm_joint9
      pid: {p: 1.0, i: 1.0}
